# Generated by Django 4.2.30 on 2026-07-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_network_order_payment_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_network',
            field=models.CharField(blank=True, choices=[('mtn', 'MTN Mobile Money'), ('telecel', 'Telecel Cash'), ('at', 'AT Money'), ('bank', 'Bank Transfer / GCB / EcoBank'), ('other', 'Other manual payment option')], max_length=50, null=True),
        ),
    ]
