# Generated by Django 4.2.30 on 2026-07-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='MED Computers', max_length=255)),
                ('location', models.CharField(default='DIRECTLY OPPOSITE TO AIRTEL TIGO OFFICE, TAMALE.', max_length=255)),
                ('phone_1', models.CharField(default='0549128355', max_length=50)),
                ('phone_2', models.CharField(default='0508800955', max_length=50)),
                ('whatsapp_number', models.CharField(default='233549128355', max_length=50)),
                ('momo_number', models.CharField(default='0549128355', max_length=50)),
                ('momo_name', models.CharField(default='MED COMPUTERS', max_length=150)),
            ],
        ),
    ]
